name: 'dbtpyth_demo'
version: '1.0.0'
config-version: 2

profile: 'dbtpyth_demo'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  dbtpyth_demo:
    +schema: raw

models:
  dbtpyth_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
